### ISSUE TITLE
FOR W21 (not for F20): replace hard coded department list with API call

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-courses-search#82] opened 2020-12-10 05:45 UTC
In `javascript/src/main/components/Statistics/DepartmentFormSelect.js` there is a hard coded list of departments.  Replace this with a backend service that gets this list of departments from the api:

`https://api.ucsb.edu/students/lookups/v1/departments`

**Comment by btk5h** [comment] 2021-05-06 22:43
Duplicate of #19

**Closed by btk5h** 2021-05-06 22:43 UTC
Labels: W21
